### ISSUE TITLE
ds package still uses golang.org/x/exp/slices

### ISSUE THREAD

**Issue by Bo0mer** [mokiat/gog#31]
Thanks for this awesome set of packages :star:

The `ds` package has references to the x/exp/slices package, which could be replaced by the slices package.

Links to the relevant code lines that could be switched to use the official slices package:
* https://github.com/mokiat/gog/blob/dba7e48413995b50c0181fca8cca7d9d96fb3347/ds/stack.go#L3
* https://github.com/mokiat/gog/blob/dba7e48413995b50c0181fca8cca7d9d96fb3347/ds/list.go#L3
* https://github.com/mokiat/gog/blob/dba7e48413995b50c0181fca8cca7d9d96fb3347/ds/heap.go#L3

Best regards,
Ivan

**Comment by mokiat** [comment]
Thanks.

Turns out I was also able to get rid of `x/exp/maps` as well, meaning that the whole `golang.org/x/exp` is now no longer a dependency.
